// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kphkxykohagzdyhuasxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaGt4eWtvaGFnemR5aHVhc3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MjYwOTEsImV4cCI6MjA1NzAwMjA5MX0.JraUE45S-dCeKrHIrmo6fFhVlpLiTVTiTTuXLJq84WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);